# Generated by Django 5.2.13 on 2026-04-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('Rollno', models.IntegerField(primary_key=True, serialize=False)),
                ('Sname', models.CharField(max_length=100)),
                ('Sage', models.IntegerField()),
                ('Perc', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
    ]
